apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam:::role/AWS-DevSecOps-Netflix-CB-Role
      username: AWSDevSecOpsNetflixCBRole
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system