apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::898855110204:role/eksctl-netflix-prod-nodegroup-ng-1-NodeInstanceRole-XtQW6R25GHTq
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::898855110204:role/AWS-DevSecOps-Netflix-CB-Role
      username: AWSDevSecOpsNetflixCBRole
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system